name:                relocant
version:             1.0.0
synopsis:            This is relocant
description:         See README.markdown
license:             BSD2
author:              Matvey Aksenov
maintainer:          matvey.aksenov@@gmail.com
copyright:           2024 Matvey Aksenov
extra-source-files:
  - README.markdown
  - CHANGELOG.markdown

custom-setup:
  dependencies:
    - base
    - Cabal
    - directory
    - filepath
    - process

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - ImportQualifiedPost
  - NoFieldSelectors
  - OverloadedStrings

library:
  dependencies:
    - envparse
  source-dirs:
    src
  other-modules:
    - Meta_relocant
    - Paths_relocant
  ghc-options:
    - -funbox-strict-fields
    - -Wall
    - -Wno-incomplete-uni-patterns
    - -Werror


tests:
  spec:
    dependencies:
      - relocant
      - hspec
    source-dirs:
      test
    main:
      Spec.hs
    ghc-options:
      - -freduction-depth=0
      - -Wall
      - -Wno-incomplete-uni-patterns
      - -Werror
      - -threaded
      - -with-rtsopts=-N

