name:                relocant
version:             1.0.0
synopsis:            A PostgreSQL migration CLI tool and library
description:
  relocant documentation is at https://github.com/supki/relocant
license:             BSD2
author:              Matvey Aksenov
maintainer:          matvey.aksenov@gmail.com
copyright:           2024 Matvey Aksenov
extra-source-files:
  - README.markdown
  - CHANGELOG.markdown

custom-setup:
  dependencies:
    - base
    - Cabal
    - directory
    - filepath
    - process

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - ImportQualifiedPost
  - NoFieldSelectors
  - OverloadedStrings
  - OverloadedRecordDot
  - StrictData

library:
  dependencies:
    - aeson
    - bytestring
    - crypton
    - directory
    - envparse
    - filepath
    - memory
    - optparse-applicative
    - postgresql-simple
    - process
    - text
    - time
  source-dirs:
    src
  other-modules:
    - Meta_relocant
    - Paths_relocant
  ghc-options:
    - -funbox-strict-fields
    - -Wall
    - -Wno-incomplete-uni-patterns
    - -Werror

executables:
  relocant:
    dependencies:
      - relocant
    source-dirs:
      driver
    main:
      Main.hs
    ghc-options:
      - -Wall
      - -Wno-incomplete-uni-patterns
      # - -Werror
      - -threaded
      - -with-rtsopts=-N

tests:
  spec:
    dependencies:
      - relocant
      - bytestring
      - crypton
      - filepath
      - hspec
      - postgresql-simple
      - random
      - temporary
      - text
    source-dirs:
      test
    main:
      Main.hs
    ghc-options:
      - -freduction-depth=0
      - -Wall
      - -Wno-incomplete-uni-patterns
      - -Werror
      - -threaded
      - -with-rtsopts=-N
